### ISSUE TITLE
Error in AOT mode

### ISSUE THREAD

**Issue by STheFox** [rednez/angular-user-idle#6]
Following errors appear when building in AOT mode:

```
[0m[1m[31mERROR in ./node_modules/angular-user-idle/user-idle.config.ts[39m[22m[0m
[0m[1m[31mModule build failed: Error: *************/node_modules/angular-user-idle/user-idle.config.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.[39m[22m[0m
[0m[1m[31mThe missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).[39m[22m[0m
[0m[1m[31m    at AngularCompilerPlugin.getCompiledFile (**********/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)[39m[22m[0m
[0m[1m[31m    at plugin.done.then (**********/node_modules/@ngtools/webpack/src/loader.js:467:39)[39m[22m[0m
[0m[1m[31m    at <anonymous>[39m[22m[0m
[0m[1m[31m    at process._tickCallback (internal/process/next_tick.js:160:7)[39m[22m[0m
[0m[1m[31mERROR in ./node_modules/angular-user-idle/user-idle.module.ts[39m[22m[0m
[0m[1m[31mModule build failed: Error: **********/node_modules/angular-user-idle/user-idle.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.[39m[22m[0m
[0m[1m[31mThe missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).[39m[22m[0m
[0m[1m[31m    at AngularCompilerPlugin.getCompiledFile (**********/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)[39m[22m[0m
[0m[1m[31m    at plugin.done.then (**********/node_modules/@ngtools/webpack/src/loader.js:467:39)[39m[22m[0m
[0m[1m[31m    at <anonymous>[39m[22m[0m
[0m[1m[31m    at process._tickCallback (internal/process/next_tick.js:160:7)[39m[22m[0m
[0m[1m[31mERROR in ./node_modules/angular-user-idle/user-idle.service.ts[39m[22m[0m
[0m[1m[31mModule build failed: Error: **********/node_modules/angular-user-idle/user-idle.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.[39m[22m[0m
[0m[1m[31mThe missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).[39m[22m[0m
[0m[1m[31m    at AngularCompilerPlugin.getCompiledFile (**********/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)[39m[22m[0m
[0m[1m[31m    at plugin.done.then (**********/node_modules/@ngtools/webpack/src/loader.js:467:39)[39m[22m[0m
[0m[1m[31m    at <anonymous>[39m[22m[0m
[0m[1m[31m    at process._tickCallback (internal/process/next_tick.js:160:7)[39m[22m[0m
```

**Comment by krishna139** [comment]
I am still facing same issue. can you please provide solution for it. it is working properly in dev env , but not in production env.

**Comment by STheFox** [comment]
@krishna139 I temporarily fixed it by adding these lines to my tsconfig.json:
```
  "include": [
    "src/main.ts",
    "src/polyfills.ts",
    "node_modules/angular-user-idle/*.ts"
  ]
```

**Comment by rednez** [comment]
Please provide more details about tools you use for building (angular-ci, manual webpack's project etc.) and your configs.
Otherwise, I will have to close the task due to insufficient input information.

On my tests angular-ci project building is success for dev and prod env.
