### ISSUE TITLE
Error when compiling in production mode on Angular 5.

### ISSUE THREAD

**Issue by jjayaraman** [rednez/angular-user-idle#8]
Hi @rednez 

Thanks for the nice module.
I get the below error when compiling in production mode on Angular 5.
I am using your v1.1.0
Can you please help?

Command used:  ng build --prod --bh /sam/ --d /sam/

It works fine with the command: ng build 

Cheers
Jay

ERROR in ./node_modules/angular-user-idle/user-idle.config.ts
Module build failed: Error: /var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/angular-user-idle/user-idle.config.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/angular-user-idle/user-idle.module.ts
Module build failed: Error: /var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/angular-user-idle/user-idle.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/angular-user-idle/user-idle.service.ts
Module build failed: Error: /var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/angular-user-idle/user-idle.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/var/lib/jenkins/workspace/da-sam-node-deploy/sam-client/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by rednez** [comment]
I cannot reproduce problem because I never used --bh and --d flags and didn't not tested ver 1.1.0 in that cases.
I can help you just to advice to use ver. 2.0.0 builded by Angular CLI 6.
I don't plan to support 1.x because it is deprecated.
